DROP TABLE IF EXISTS customer;

CREATE TABLE customer (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  pin VARCHAR(250) NOT NULL,
  type VARCHAR(250) DEFAULT NULL,
  balance DOUBLE DEFAULT 0.0
);
